

export const types = {
    CREATE_TODO: 'CREATE_TODO',
    DELETE_TODO: 'DELETE_TODO',
    CHANGE_STATUS: 'CHANGE_STATUS',
    CLEAR_TODO: 'CLEAR_TODO',
    CHANGE_TODO: 'CHANGE_TODO',
    CHANGE_TITLE: 'CHANGE_TITLE',
    CHANGE_TITLE_FROM_INPUT: 'CHANGE_TITLE_FROM_INPUT'
}